---
- name: Install Fresh Install Packages
  hosts: app
  become: true

  tasks:
  - name: Add Brave Repo
    yum_repository:
      name: brave-repo
      description: Brave Repository
      baseurl: https://brave-browser-rpm-release.s3.brave.com/x86_64/

  - rpm_key:
      state: present
      key: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc

  - name: Install Brave Browser
    yum:
      name: brave-browser
      state: present
