---
- name: Setup Fresh Centos 8 Instal
  hosts: app
  become: yes

  tasks:
  - name: Install Flatpak
    yum:
      name: flatpak
      state: present

  - name: Add the flathub flatpak repository remote to the user installation
    flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

  - name: Install GNOME Clocks
    flatpak:
      name: org.gnome.clocks
      state: present
