---
- name: Setup Fresh Debian 10 Install
#  hosts: localhost
#  connection: local
  hosts: apps
  become: yes

  tasks:
  - name: Add VirtualBox GPG Key
    apt_key:
      url: https://www.virtualbox.org/download/oracle_vbox.asc
      state: present

  - name: Add VirtualBox GPG Key
    apt_key:
      url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
      state: present

  - name: Add Brave GPG Key
    apt_key:
      url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
      state: present

  - name: Add VirtualBox Repo
    apt_repository:
      repo: deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian buster contrib
      state: present

  - name: Add Brave Repo
    apt_repository:
      repo: deb https://brave-browser-apt-release.s3.brave.com/ stable main
      state: present

  - name: Update all packages to the latest version
    apt:
      upgrade: dist

  - name: Add Software Properties Common
    apt:
      name: software-properties-common
      state: present

  - name: Copy Atom
    copy:
      src: ./files/atom-amd64.deb
      dest: /tmp/atom-amd64.deb

  - name: Install Atom
    apt:
      deb: /tmp/atom-amd64.deb

  - name: Install Brasero
    apt:
      name: brasero
      state: present

  - name: Install Brave Browser Pre-Reqs
    apt:
      name:
        - apt-transport-https
        - curl
      state: present

  - name: Install Brave browser
    apt:
      name: brave-browser
      state: present

  - name: Install Chrome
    apt:
      deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

  - name: Install Chromium
    apt:
      name: chromium
      state: present

  - name: Copy Folding@Home Client
    copy:
      src: ./files/fahclient_7.5.1_amd64.deb
      dest: /tmp/fahclient_7.5.1_amd64.deb

  - name: Install Folding@Home Client
    apt:
      deb: /tmp/fahclient_7.5.1_amd64.deb

  - name: Copy Folding@Home Control
    copy:
      src: ./files/fahcontrol_7.5.1-1_all.deb
      dest: /tmp/fahcontrol_7.5.1-1_all.deb

  - name: Install Folding@Home Control
    apt:
      deb: /tmp/fahcontrol_7.5.1-1_all.deb

  - name: Install Filezilla
    apt:
      name: filezilla
      state: present

  - name: Install Firefox
    apt:
      name: firefox-esr
      state: present

  - name: Install Git
    apt:
      name: git
      state: present

  - name: Install Vim
    apt:
      name: vim
      state: present

  - name: Install GIMP
    apt:
      name: gimp
      state: present

  - name: Install Gparted
    apt:
      name: gparted
      state: present

  - name: Install Handbrake
    apt:
      name: handbrake
      state: present

  - name: Install HexChat
    apt:
      name: hexchat-common
      state: present

  - name: Install Htop
    apt:
      name: htop
      state: present

  - name: Install Thunderbird
    apt:
      name: thunderbird
      state: present

  - name: Install Inkscape
    apt:
      name: inkscape
      state: present

  - name: Install  K3B
    apt:
      name: k3b
      state: present

  - name: Install KeePassX
    apt:
      name: keepassx
      state: present

  - name: Install LibreOffice
    apt:
      name: libreoffice
      state: present

  - name: Install Virtualbox
    apt:
      name: virtualbox-6.0
      state: present

  - name: Download VirtualBox Extension Pack
    # sudo VBoxManage extpack install Oracle_VM_VirtualBox_Extension_Pack-6.0.10.vbox-extpack to install after running playbook
    # required gui approval of terms
    get_url:
      url: https://download.virtualbox.org/virtualbox/6.0.10/Oracle_VM_VirtualBox_Extension_Pack-6.0.10.vbox-extpack
      dest: /tmp/Oracle_VM_VirtualBox_Extension_Pack-6.0.10.vbox-extpack

  - name: Copy Plex Media Server
    copy:
      src: ./files/plexmediaserver_1.19.1.2645-ccb6eb67e_amd64.deb
      dest: /tmp/plexmediaserver_1.19.1.2645-ccb6eb67e_amd64.deb

  - name: Install Plex Media Server
    apt:
      deb: /tmp/plexmediaserver_1.19.1.2645-ccb6eb67e_amd64.deb

  - name: Install Vagrant
    apt:
      name: vagrant
      state: present

  - name: Install OpenJDK
    apt:
      name: openjdk-11-jre
      state: present

  - name: Install Rhythmbox
    apt:
      name: rhythmbox
      state: present

  - name: Install Simple Scan
    apt:
      name: simple-scan
      state: present

  - name: Install Sound Juicer
    apt:
      name: sound-juicer
      state: present

  - name: Download Teamviewer
    get_url:
      url: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
      dest: /tmp/teamviewer.deb

  - name: Install Teamviewer
    apt:
      deb: /tmp/teamviewer.deb

  - name: Install Transmission
    apt:
      name: transmission
      state: present

  - name: Install VLC
    apt:
      name: vlc
      state: present

  - name: Copy Private Internet Access VPN installer
    copy:
      src: ./files/pia-linux-1.8-04193.run
      dest: /tmp/pia-linux-1.8-04193.run

  - name: Install PIA VPN
    shell: sh /tmp/pia-linux-1.8-04193.run
    become: false

  - name: Install Flatpak
    apt:
      name: flatpak
      state: present

  - name: Add the flathub flatpak repository remote to the user installation
    flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

  - name: Install Spotify
    flatpak:
      name: com.spotify.Client
      state: present

  - name: Install Nload
    apt:
      name: nload
      state: present

  - name: Install Psensor
    apt:
      name: psensor
      state: present

  # - name: Install
  #   apt:
  #     name:
  #     state: present

  # - name: Add Woeusb Repo (WebUpd8)
  #   shell: add-apt-repository ppa:nilarimogard/webupd8
  #
  # - name: Install Woeusb
  #   apt:
  #     name: woeusb
  #     state: present
  # ppa wont install for debian systems, have to build from source
