---
- name: Setup Fresh Centos 8 Instal
  hosts: app
#  hosts: localhost
#  connection: local
  become: yes
  # Download the required rpm's into the files directory before kicking of playbook and change variable names as appropiate
  vars:
    pia_package: pia-linux-1.8-04193.run

  tasks:
  - name: Add EPEL Repo
    yum:
      name: epel-release
      state: present

  - name: Add RPM Fusion Repo
    yum:
      name: https://download1.rpmfusion.org/free/el/rpmfusion-free-release-8.noarch.rpm
      state: present

  - name: Add Geekery Repo
    yum:
      name: http://geekery.altervista.org/geekery/el8/x86_64/geekery-release-8-2.noarch.rpm
      state: present

  - name: Copy Plex Media Server Repo
    copy:
      src: plex.repo
      dest: /etc/yum.repos.d/plex.repo
      mode: '0644'

  - name: Download Virtualbox Repo
    get_url:
      url: https://download.virtualbox.org/virtualbox/rpm/el/virtualbox.repo
      dest: /etc/yum.repos.d/virtualbox.repo
      mode: '0644'

  - name: Add Power Tools Repo
    shell: yum config-manager --set-enabled PowerTools
    args:
      warn: no

  - name: Add Nux Repo
    yum:
      name: http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm
      state: present

  - name: Upgrade All Packages
    yum: name=* state=latest

  - name: Install Snap
    yum:
      name: snapd
      state: present

  - name: Install Git
    yum:
      name: git
      state: present

  - name: Install Make
    yum:
      name: make
      state: present

  - name: Install KDEConnect
    yum:
      name: kdeconnectd
      state: present

  - name: Install K3B
    yum:
      name: k3b
      state: present

  - name: Copy Private Internet Access VPN installer
    copy:
      src: ./files/{{ pia_package }}
      dest: /tmp/{{ pia_package }}

  - name: Install PIA VPN
    shell: sh /tmp/{{ pia_package }}
    become: false

  - name: Install XSane
    yum:
      name: xsane
      state: present

  - name: Install Python3
    yum:
      name: python3
      state: present

  - name: Install ffmpeg
    yum:
      name:
        - ffmpeg
        - ffmpeg-devel
      state: present

  - name: Install Handbrake
    yum:
      name: HandBrake
      state: present

  - name: Download & Install Vagrant
    yum:
      name: https://releases.hashicorp.com/vagrant/2.2.6/vagrant_2.2.6_x86_64.rpm
      state: present

  - name: Download & Install Google Chome
    yum:
      name: https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
      state: present

  - name: Install Tree
    yum:
      name: tree
      state: present

  - name: Download and Unarchive Rar and Unrar Tools
    unarchive:
      src: https://www.rarlab.com/rar/rarlinux-x64-5.8.0.tar.gz
      dest: /tmp/
      remote_src: yes

  - name: Copy Unrar Tool To Binaries
    copy:
      remote_src: yes
      src: /tmp/rar/unrar
      dest: /usr/local/bin/unrar
      mode: '0755'

  - name: Copy Rar Tool To Binaries
    copy:
      remote_src: yes
      src: /tmp/rar/rar
      dest: /usr/local/bin/rar
      mode: '0755'

  - name: Check Tar Is Installed
    yum:
      name: tar
      state: present

  - name: Check Gzip Is Installed
    yum:
      name: gzip
      state: present

  - name: Download Tagspaces App Image
    get_url:
      url: https://www.tagspaces.org/downloads/tagspaces-linux64.AppImage
      dest: /opt
      mode: '0775'

  - name: Register Tagspaces App Image Name
    shell: ls /opt/tagspaces*
    register: tagspaces_app_image

  - name: Install Tagspaces Prerequesite Libraries
    yum:
      name:
        - nss
        - gdk-pixbuf2
        - gtk3
      state: present

  - name: Install Virtualbox v6 Build Tools
    yum:
      name:
        - binutils
        - kernel-devel-4.18.0-80.el8.x86_64
        - kernel-headers
        - libgomp
        - make
        - patch
        - gcc
        - glibc-headers
        - glibc-devel
        - dkms
      state: present

  - name: Install Virtualbox v6
    yum:
      name: VirtualBox-6.1
      state: present

  - name: Virtualbox Rebuild Kernel Paramters
    command: /usr/lib/virtualbox/vboxdrv.sh setup

  - name: Install Plex Media Server
    yum:
      name: plexmediaserver
      state: present

  - name: Install Flatpak
    yum:
      name: flatpak
      state: present

  - name: Add Flapak Flathub Repository
    flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

  - name: Install HandBrake
    flatpak:
      name: fr.handbrake.ghb
      state: present

  - name: Install Calibre
    flatpak:
      name: com.calibre_ebook.calibre
      state: present

  - name: Install Tor Browser
    flatpak:
      name: com.github.micahflee.torbrowser-launcher
      state: present

  - name: Install Audacity
    flatpak:
      name: org.audacityteam.Audacity
      state: present

  - name: Install KDE Connect Indicator
    flatpak:
      name: com.github.bajoja.indicator-kdeconnect
      state: present

  - name: Install GNOME Clocks
    flatpak:
      name: org.gnome.clocks
      state: present

  - name: Install Spotify
    flatpak:
      name: com.spotify.Client
      state: present

  - name: Install Visual Studio Code
    flatpak:
      name: com.visualstudio.code
      state: present

  - name: Install Steam
    flatpak:
      name: com.valvesoftware.Steam
      state: present

  - name: Install Slack
    flatpak:
      name: com.slack.Slack
      state: present

  - name: Install FileZilla
    flatpak:
      name: org.filezillaproject.Filezilla
      state: present

  - name: Download and Install Teamviewer
    yum:
      name: https://download.teamviewer.com/download/linux/teamviewer.x86_64.rpm
      state: present

  - name: Install Transmission
    yum:
      name: transmission
      state: present

  - name: Install Transmission Daemon
    yum:
      name: transmission-daemon
      state: present

  - name: Install Wget
    yum:
      name: wget
      state: present

  - name: Install Vim
    yum:
      name: vim
      state: present

  - name: Install GIMP
    yum:
      name: gimp
      state: present

  - name: Install Firefox
    yum:
      name: firefox
      state: present

  - name: Install Rhythmbox
    yum:
      name: rhythmbox.x86_64
      state: present

  - name: Install HexChat
    yum:
      name: hexchat.x86_64
      state: present

  - name: Install Inkscape
    yum:
      name: inkscape
      state: present

  - name: Install LibreOffice Writer
    yum:
      name: libreoffice-writer
      state: present

  - name: Install LibreOffice Spreadsheet
    yum:
      name: libreoffice-calc
      state: present

  - name: Install Nano
    yum:
      name: nano.x86_64
      state: present

  - name: Install Gparted
    yum:
      name: gparted
      state: present

  - name: Install KeepassXC
    yum:
      name: keepassxc
      state: present

  - name: Install Thunderbird
    yum:
      name: thunderbird
      state: present

  - name: Install Ansible
    yum:
      name: ansible
      state: present

  - name: Download and Install Atom
    yum:
      name: https://atom.io/download/rpm
      state: present

  - name: Install Htop
    yum:
      name: htop
      state: present

  - name: Install VLC
    yum:
      name: vlc
      state: present

  - name: Add Brave Repo
    yum_repository:
      name: brave-repo
      description: Brave Repository
      baseurl: https://brave-browser-rpm-release.s3.brave.com/x86_64/

  - name: Add Brave Repo GPG Key
    rpm_key:
      state: present
      key: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc

  - name: Install Brave Browser
    yum:
      name: brave-browser
      state: present
